title: Manisha Shedge
logo: /assets/img/manisha.jpg
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/manisha-shedge-a5563b172/">LinkedIn</a> |
  <a href="https://github.com/manisha0399">GitHub</a>
  
  </p>



theme: jekyll-theme-minimal
